### ISSUE TITLE
Question : Setting form size limit

### ISSUE THREAD

**Issue by makiwara-fr** [magiclen/rocket-multipart-form-data#10]
I cannot find ways to set a size limit to the form data.

I've try through rocket.toml forms limit without success
Any way to do it ?

Thanks

**Comment by magiclen** [comment]
To make it clear, this crate is for multipart-form-data, not for x-www-form-urlencoded which is already implemented in the Rocket framework itself.

You probably wrote something like

```toml
limits = {forms = 32768}
```

in your `Rocket.toml` file. That limitation is for x-www-form-urlencoded.

To get back to your question, for this crate, you can set a form size limit on each form field by using the `size_limit` method of a `MultipartFormDataField`. Just see the example in **README.md**.

**Comment by makiwara-fr** [comment]
Thanks ! 

indeed I tried 
`limits = {forms = 32768}`

Thinking it would inherit from rocket.
I will set it programmatically then. Thanks for the heads up
