### ISSUE TITLE
Example doesn't run as expected...

### ISSUE THREAD

**Issue by emmanuelantony2000** [magiclen/rocket-multipart-form-data#3]
I was running the examples, and it seems to me that it does not run as expected. No matter whichever file I try, the output is "Please input a file."

**Comment by magiclen** [comment]
Can't you reproduce that?

**Comment by emmanuelantony2000** [comment]
It was a mistake from my part. By the way can i contribute some refactoring to the library?

**Comment by magiclen** [comment]
Of course you can. Just submit the PR(s).

**Comment by emmanuelantony2000** [comment]
Other than refactoring, should the formatting (rustfmt) be a separate pr?

**Comment by magiclen** [comment]
I think it is not necessary to run rustfmt on this project for now. I will do that for my all Rust projects with the same `rustfmt.toml` file in the future.
